lkm: dev
directboot: "true"
model: "SA6400"
build: "42962"
sn: "0000XXXBN4YEE"
maxdisks: ""
layout: qwerty
keymap: ""
zimage-hash: "a44e94a22ddfb35e1b4d7b25253f6d0e266b0b675a4ca965023326a0884a2cf7"
ramdisk-hash: "269091f07901bbb72c23b6349a91d01259143debf721f03521f6ca81cdd1c079"
cmdline:
  netif_num: "4"
  mac1: 7e21363bcd1b
  mac2: 7e21363bcd3b
  mac3: 7e21363bcd5b
  mac4: 7e21363bcd7b
  i915.enable_guc: "2"
synoinfo:
  support_disk_compatibility: no
  support_memory_compatibility: no
  support_led_brightness_adjustment: no
  rss_server: https://raw.githubusercontent.com/fbelavenuto/arpl/main/rss.xml
  rss_server_ssl: https://raw.githubusercontent.com/fbelavenuto/arpl/main/rss.xml
  rss_server_v2: https://raw.githubusercontent.com/fbelavenuto/arpl/main/rss.json
addons:
  acpid: ""
  console: ""
  disks: ""
  misc: ""
  dbgutils: ""
modules:
  acpi-cpufreq: ""
  alx: ""
  e1000: ""
  e1000e: ""
  igb: ""
  igc: ""
  ixgb: ""
  ixgbe: ""
  ixgbevf: ""
  failover: ""
  mii: ""
  net_failover: ""
  r8152: ""
  r8168: ""
  r8169: ""
  usbkbd: ""
  usbmouse: ""
  virtio: ""
  virtio_mmio: ""
  virtio_net: ""
  virtio_pci: ""
  virtio_ring: ""
  virtio_scsi: ""
original-mac: 7e21463bcd4b
vid: "0x46f4"
pid: "0x0001"