lkm: dev
directboot: "true"
model: "SA6400"
build: "64570"
sn: "2270XXXBN4YEE"
maxdisks: ""
layout: qwerty
keymap: ""
redirect-linuxrc-output: "true"
ramdisk-hash: "48227142edd6ea969ebec6c3160c9939aef5a853e1ba2556d3401a68c5953357"
zimage-hash: "6fd6d57b5b856569b3c48e3a416c0a68fc8bcd45db1ebd09bdb5b79f4dfc3300"
cmdline:
  netif_num: "4"
  mac1: 7e21363bcd10
  mac2: 7e21363bcd30
  mac3: 7e21363bcd50
  mac4: 7e21363bcd70
  i915.enable_guc: "2"
synoinfo:
  support_disk_compatibility: no
  support_memory_compatibility: no
  support_led_brightness_adjustment: no
  supportraidgroup: "no"
  support_syno_hybrid_raid: "yes"
  support_m2_pool: "yes"
  internal_disk_without_led_mask: "yes"
  support_led_behavior_v2: "no"
  support_leds_atmega1608: "no"
  support_oob_ctl: "no"
  rss_server: https://raw.githubusercontent.com/fbelavenuto/arpl/main/rss.xml
  rss_server_ssl: https://raw.githubusercontent.com/fbelavenuto/arpl/main/rss.xml
  rss_server_v2: https://raw.githubusercontent.com/fbelavenuto/arpl/main/rss.json
addons:
  acpid: ""
  console: ""
  kvm-intel: ""
  misc: ""
  dbgutils: ""
  qemu-ga: ""
  entware: ""
  bpftrace: ""
  lshw: ""
  kernel-headers: ""
  patches: "1"
modules:
  acpi-cpufreq: ""
  # hba
  mpt3sas: ""
  aacraid: ""
  # gpu
  i915: ""
  vmwgfx: ""
  # network
  alx: ""
  atlantic: ""
  e1000: ""
  e1000e: ""
  igb: ""
  igc: ""
  ixgb: ""
  ixgbe: ""
  ixgbevf: ""
  r8125: ""
  r8152: ""
  r8169: ""
  vmxnet3: ""
  # virtio
  virtio_console: ""
  virtio_mmio: ""
  virtio_net: ""
  virtio_pci: ""
  virtio_ring: ""
  virtio_scsi: ""
original-mac: 7e21463bcd4b
vid: "0x46f4"
pid: "0x0001"